task_breakdown:
  description: >
    Carefully analyze the project_requirements for the {project_type}
    project and break them down into individual tasks. Define each
    task's scope in detail, set achievable timelines, and ensure that
    all dependencies are accounted for:

    {project_requirements}


    Team members:

    {team_members}
  expected_output: >
    A comprehensive list of tasks with detailed descriptions, timelines,
    dependencies, and deliverables. 

time_resource_estimation:
  description: >
    Thoroughly evaluate each task in the {project_type} project to
    estimate the time, resources, and effort required.
    Use historical data, task complexity, and available resources to
    provide a realistic estimation for each task.
  expected_output: >
    A detailed estimation report outlining the time, resources, and
    effort required for each task in the {project_type} project.
    Your final report MUST include a summary of any risks or
    uncertainties associated with the estimations.

resource_allocation:
  description: >
    Strategically allocate tasks for the {project_type} project to
    {team_members} based on their skills, availability, and current
    workload. Ensure that each task is assigned to the most suitable
    team member and that the workload is evenly distributed. 
    If the same task is allocated to multiple team members,
    split the task into logical subtasks with unique and clear names
    and allocate one team member at most to each subtask. 


  expected_output: >
    A resource allocation dictionary showing which rousource from the available {team_members} is
    responsible for each task in the {project_type} project, along with
    start and end dates. Your final output MUST also include a text summary
    explaining the rationale behind each allocation decision.
